# Generated by Django 4.0.2 on 2023-01-11 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_alter_sheba_servicecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.IntegerField(max_length=300)),
                ('serviceuserid', models.IntegerField(max_length=300)),
                ('userid', models.IntegerField(max_length=300)),
                ('serviceid', models.IntegerField(max_length=300)),
                ('orderservicetitle', models.CharField(max_length=300)),
                ('orderserviceprice', models.CharField(max_length=300)),
                ('orderdate', models.DateField()),
                ('orderaddress', models.CharField(max_length=300)),
                ('orderphoneno', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ordernew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.IntegerField(max_length=300)),
                ('serviceuserid', models.IntegerField(max_length=300)),
                ('userid', models.IntegerField(max_length=300)),
                ('serviceid', models.IntegerField(max_length=300)),
                ('orderservicetitle', models.CharField(max_length=300)),
                ('orderserviceprice', models.CharField(max_length=300)),
                ('orderdate', models.DateField()),
                ('orderaddress', models.CharField(max_length=300)),
                ('orderphoneno', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cartanother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetitle', models.CharField(max_length=300)),
                ('serviceprice', models.CharField(max_length=300)),
                ('serviceuseridnum', models.IntegerField(max_length=300)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.sheba')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
