# Generated by Django 4.1.5 on 2023-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartanother', '0002_cartanothernew'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='accept_or_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
