# Generated by Django 4.1.5 on 2023-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartanother', '0003_ordernew_accept_or_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
