# Generated by Django 4.0.2 on 2022-08-10 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetitle', models.CharField(max_length=100)),
                ('servicedetails', models.CharField(max_length=100)),
                ('servicecategory', models.CharField(choices=[('service1', 'service1'), ('service2', 'service2'), ('service3', 'service3'), ('service4', 'service4')], default='service1', max_length=10)),
                ('serviceprice', models.IntegerField(max_length=100)),
                ('servicelocation', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chattagram')], default='Dhaka', max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
