# Generated by Django 4.0.2 on 2022-08-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheba',
            old_name='seller',
            new_name='user',
        ),
    ]
