# Generated by Django 4.0.2 on 2022-11-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_seller_sheba_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheba',
            name='servicecategory',
            field=models.CharField(choices=[('service1', 'service1'), ('service2', 'service2'), ('service3', 'service3'), ('service4', 'service4')], default='service1', max_length=100),
        ),
    ]
