# Generated by Django 4.1.5 on 2023-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_sheba_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheba',
            name='featureservice',
            field=models.BooleanField(default=False),
        ),
    ]
