# Generated by Django 4.1.5 on 2023-02-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_sheba_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheba',
            name='servicecategory',
            field=models.CharField(choices=[('IT Service', 'IT Service'), ('Cleaning Service', 'Cleaning Service'), ('Electric Service', 'Electric Service'), ('others', 'others')], default='service1', max_length=100),
        ),
    ]
